#!/usr/bin/env python

import os
import shutil
import sys

def usage(saw=None):
    print("Error! Need to enter local or net on command line.")
    if saw: print("Saw " + saw)
    sys.exit(-1)

if len(sys.argv) < 2: usage();
local = "local"
net = "net"
base = "README_base.md"
out = "README.md"
localNet = sys.argv[1]
if localNet != local and localNet != net: usage();

if not os.path.exists(base):
    print("Error! Could not find file = " + base)
    sys.exit(-1)

localStr = "(http://localhost:3000/advancedLaneFinding.html"
netStr = "(http://carltonwin8.github.io/CarND-Advanced-Lane-Lines"
with open(base) as f:
    content = f.read()

if localNet == local: newContent = content.replace(netStr, localStr)
if localNet == net: newContent = content.replace(localStr, netStr)

with open(out,"w") as f:
    f.write(newContent)
